name: Report gas diff

on:
  push:
    branches:
      - main
  pull_request:
    # Optionally configure to run only for changes in specific files. For example:
    paths:
    - src/**
    - test/**
    - foundry.toml
    - remappings.txt
    - .github/workflows/foundry-gas-diff.yml

env:
  FOUNDRY_PROFILE: default
  INFURA_KEY: ${{ secrets.INFURA_KEY }}
  GC_RPC: ${{ secrets.GC_RPC }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  compare_gas_reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Add any step generating a gas report to a temporary file named gasreport.ansi. For example:
      - name: Run tests
        run: forge test --gas-report > gasreport.ansi # <- this file name should be unique in your repository!
        env:
          # make fuzzing semi-deterministic to avoid noisy gas cost estimation
          # due to non-deterministic fuzzing (but still use pseudo-random fuzzing seeds)
          FOUNDRY_FUZZ_SEED: 0x${{ github.event.pull_request.base.sha || github.sha }}

      - name: Compare gas reports
        uses: Rubilmax/foundry-gas-diff@v3.13.6
        with:
          report: gasreport.ansi
          summaryQuantile: 0.9
          sortCriteria: avg,max
          sortOrders: desc,asc
          ignore: test-foundry/**/*
          artifactName: gas_report_${{ github.head_ref || github.ref_name }}
        id: gas_diff

      - name: Add gas diff to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # delete the comment in case changes no longer impact gas costs
          delete: ${{ !steps.gas_diff.outputs.markdown }}
          message: ${{ steps.gas_diff.outputs.markdown }}
